# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2abfb84be98235431d3196358cd447c0b36002cf1c86567cba5b41bd52d2f0094c2f79a6d6ddff03797b9fb2953e3c4dc5cc2a529e0015004c2e0f1b2b4d8bf0

test:
  secret_key_base: 568406ab04aebbfdb14db3b4db4a8e4651bd89a9ed6f3bb00edb5b8b0f58824cd945ec1210dd39d9190668ea38f344fb569a5be0cb53689d85989033cedff08d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
